app:
  port: 8888

db:
  name: "asset-tracker"
  userName: "postgres"
  userPassword: "password"
  schema: "asset_tracker_schema"
  url: "jdbc:postgresql://localhost:41110/asset-tracker"

jooq:
  runCodeGeneration: false
  directory: "lib/src/main/java"
  sqlMigrationFilesLocation: "lib/src/main/resources/db/migration/*.sql"

flyway:
  runMigration: false
  locations: "filesystem:lib/src/main/resources/db/migration"
