app:
  port: 8888

db:
  name: "asset-tracker"
  userName: "postgres"
  userPassword: "password"
  schema: "asset_tracker_schema"
  url: "jdbc:postgresql://localhost:41110/asset-tracker"
  port: 41110
  host: "localhost"

jooq:
  runCodeGeneration: false
  directory: "lib/src/main/java"
  sqlMigrationFilesLocation: "app/src/main/resources/db/migration/*.sql"

flyway:
  runMigration: true